import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Separator } from '@/components/ui/separator';
import Layout from '@/components/layout/layout';
import {
  Brain,
  Mic,
  BookOpen,
  ArrowRight,
  CheckCircle2,
  Sparkles,
  Play,
  Zap,
} from 'lucide-react';

export default function HomePage() {
  return (
    <Layout>
      <div className="space-y-12 max-w-6xl mx-auto">
        {/* Hero Section - Simplified */}
        <div className="text-center space-y-6 py-8">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-blue-50 text-blue-700 rounded-full text-sm font-medium">
            <Sparkles className="w-4 h-4" />
            AI-Powered Learning Platform
          </div>
          <h1 className="text-4xl font-bold text-gray-900 sm:text-5xl">
            Master Skills with
            <span className="text-blue-600"> AI Practice</span>
          </h1>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Three powerful features to accelerate your learning journey. Choose
            your path below.
          </p>
        </div>

        {/* Main Features */}
        <Tabs defaultValue="practice" className="w-full">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="practice" className="gap-2">
              <Brain className="w-4 h-4" />
              Practice
            </TabsTrigger>
            <TabsTrigger value="interview" className="gap-2">
              <Mic className="w-4 h-4" />
              Interview
            </TabsTrigger>
            <TabsTrigger value="review" className="gap-2">
              <BookOpen className="w-4 h-4" />
              Review
            </TabsTrigger>
          </TabsList>

          {/* Practice Tab */}
          <TabsContent value="practice" className="space-y-6 mt-6">
            <Card className="border-2 border-purple-100">
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div className="space-y-2">
                    <CardTitle className="text-2xl flex items-center gap-2">
                      <Brain className="w-6 h-6 text-purple-600" />
                      AI-Powered Practice
                    </CardTitle>
                    <CardDescription className="text-base">
                      Test your knowledge with intelligent quizzes generated by
                      AI
                    </CardDescription>
                  </div>
                  <Link to="/practice">
                    <Button
                      size="lg"
                      className="gap-2 bg-purple-600 hover:bg-purple-700"
                    >
                      Start Practice
                      <ArrowRight className="w-4 h-4" />
                    </Button>
                  </Link>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <Separator />

                <div className="grid gap-4 md:grid-cols-2">
                  <div>
                    <h4 className="font-semibold mb-3 flex items-center gap-2">
                      <Play className="w-4 h-4 text-purple-600" />
                      What You&apos;ll Get
                    </h4>
                    <ul className="space-y-2 text-sm text-gray-600">
                      <li className="flex items-start gap-2">
                        <CheckCircle2 className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                        <span>
                          AI-generated quizzes on any topic you choose
                        </span>
                      </li>
                      <li className="flex items-start gap-2">
                        <CheckCircle2 className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                        <span>
                          Customizable difficulty
                          (Beginner/Intermediate/Advanced)
                        </span>
                      </li>
                      <li className="flex items-start gap-2">
                        <CheckCircle2 className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                        <span>
                          Instant AI feedback with detailed explanations
                        </span>
                      </li>
                      <li className="flex items-start gap-2">
                        <CheckCircle2 className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                        <span>Performance tracking and recommendations</span>
                      </li>
                    </ul>
                  </div>

                  <div>
                    <h4 className="font-semibold mb-3 flex items-center gap-2">
                      <Zap className="w-4 h-4 text-yellow-600" />
                      How It Works
                    </h4>
                    <ol className="space-y-2 text-sm text-gray-600">
                      <li className="flex items-start gap-3">
                        <span className="flex items-center justify-center w-5 h-5 rounded-full bg-purple-100 text-purple-700 text-xs font-bold flex-shrink-0">
                          1
                        </span>
                        <span>Choose topic, technology, and difficulty</span>
                      </li>
                      <li className="flex items-start gap-3">
                        <span className="flex items-center justify-center w-5 h-5 rounded-full bg-purple-100 text-purple-700 text-xs font-bold flex-shrink-0">
                          2
                        </span>
                        <span>AI generates custom quiz (5-20 questions)</span>
                      </li>
                      <li className="flex items-start gap-3">
                        <span className="flex items-center justify-center w-5 h-5 rounded-full bg-purple-100 text-purple-700 text-xs font-bold flex-shrink-0">
                          3
                        </span>
                        <span>Answer questions at your own pace</span>
                      </li>
                      <li className="flex items-start gap-3">
                        <span className="flex items-center justify-center w-5 h-5 rounded-full bg-purple-100 text-purple-700 text-xs font-bold flex-shrink-0">
                          4
                        </span>
                        <span>Get instant results with AI review & tips</span>
                      </li>
                    </ol>
                  </div>
                </div>

                <Alert className="bg-purple-50 border-purple-200">
                  <Brain className="h-4 w-4 text-purple-600" />
                  <AlertTitle className="text-purple-900">
                    Powered by AI
                  </AlertTitle>
                  <AlertDescription className="text-purple-700">
                    Each quiz is unique and adapts to your chosen topic. Perfect
                    for testing specific knowledge areas.
                  </AlertDescription>
                </Alert>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Interview Tab */}
          <TabsContent value="interview" className="space-y-6 mt-6">
            <Card className="border-2 border-green-100">
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div className="space-y-2">
                    <CardTitle className="text-2xl flex items-center gap-2">
                      <Mic className="w-6 h-6 text-green-600" />
                      AI Interview Practice
                    </CardTitle>
                    <CardDescription className="text-base">
                      Realistic voice-based interview simulation with AI
                      feedback
                    </CardDescription>
                  </div>
                  <Link to="/interview/setup">
                    <Button
                      size="lg"
                      className="gap-2 bg-green-600 hover:bg-green-700"
                    >
                      Start Interview
                      <ArrowRight className="w-4 h-4" />
                    </Button>
                  </Link>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <Separator />

                <div className="grid gap-4 md:grid-cols-2">
                  <div>
                    <h4 className="font-semibold mb-3 flex items-center gap-2">
                      <Play className="w-4 h-4 text-green-600" />
                      What You&apos;ll Get
                    </h4>
                    <ul className="space-y-2 text-sm text-gray-600">
                      <li className="flex items-start gap-2">
                        <CheckCircle2 className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                        <span>Voice-based interview questions</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <CheckCircle2 className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                        <span>Audio recording and transcription</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <CheckCircle2 className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                        <span>AI analysis of your communication skills</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <CheckCircle2 className="w-4 h-4 text-green-600 mt-0.5 flex-shrink-0" />
                        <span>Detailed feedback report with scores</span>
                      </li>
                    </ul>
                  </div>

                  <div>
                    <h4 className="font-semibold mb-3 flex items-center gap-2">
                      <Zap className="w-4 h-4 text-yellow-600" />
                      How It Works
                    </h4>
                    <ol className="space-y-2 text-sm text-gray-600">
                      <li className="flex items-start gap-3">
                        <span className="flex items-center justify-center w-5 h-5 rounded-full bg-green-100 text-green-700 text-xs font-bold flex-shrink-0">
                          1
                        </span>
                        <span>Set job role, experience level & skills</span>
                      </li>
                      <li className="flex items-start gap-3">
                        <span className="flex items-center justify-center w-5 h-5 rounded-full bg-green-100 text-green-700 text-xs font-bold flex-shrink-0">
                          2
                        </span>
                        <span>AI generates relevant interview questions</span>
                      </li>
                      <li className="flex items-start gap-3">
                        <span className="flex items-center justify-center w-5 h-5 rounded-full bg-green-100 text-green-700 text-xs font-bold flex-shrink-0">
                          3
                        </span>
                        <span>Record audio responses using microphone</span>
                      </li>
                      <li className="flex items-start gap-3">
                        <span className="flex items-center justify-center w-5 h-5 rounded-full bg-green-100 text-green-700 text-xs font-bold flex-shrink-0">
                          4
                        </span>
                        <span>Receive comprehensive AI evaluation</span>
                      </li>
                    </ol>
                  </div>
                </div>

                <Alert className="bg-amber-50 border-amber-200">
                  <Mic className="h-4 w-4 text-amber-600" />
                  <AlertTitle className="text-amber-900">
                    Microphone Required
                  </AlertTitle>
                  <AlertDescription className="text-amber-700">
                    You&apos;ll need to allow microphone access for this
                    feature. Practice as many times as you want!
                  </AlertDescription>
                </Alert>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Review Tab */}
          <TabsContent value="review" className="space-y-6 mt-6">
            <Card className="border-2 border-blue-100">
              <CardHeader>
                <div className="flex items-center gap-3">
                  <div className="p-3 bg-blue-100 rounded-lg">
                    <BookOpen className="h-6 w-6 text-blue-600" />
                  </div>
                  <div>
                    <CardTitle className="text-2xl">
                      Quiz Question Review
                    </CardTitle>
                    <CardDescription>
                      Study interview questions at your own pace
                    </CardDescription>
                  </div>
                </div>
                <div className="flex gap-2 mt-4">
                  <Link to="/review">
                    <Button
                      size="lg"
                      className="bg-blue-600 hover:bg-blue-700"
                    >
                      <Play className="w-4 h-4 mr-2" />
                      Browse Questions
                      <ArrowRight className="w-4 h-4 ml-2" />
                    </Button>
                  </Link>
                </div>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* What You'll Get */}
                <div>
                  <h3 className="font-semibold text-lg mb-4 flex items-center gap-2">
                    <Sparkles className="w-5 h-5 text-blue-600" />
                    What You&apos;ll Get
                  </h3>
                  <div className="grid gap-3">
                    <div className="flex gap-3">
                      <CheckCircle2 className="h-5 w-5 text-blue-600 flex-shrink-0 mt-0.5" />
                      <div>
                        <span className="font-medium">
                          Comprehensive Question Bank
                        </span>
                        <p className="text-sm text-gray-600">
                          200+ JavaScript and CSS interview questions
                        </p>
                      </div>
                    </div>
                    <div className="flex gap-3">
                      <CheckCircle2 className="h-5 w-5 text-blue-600 flex-shrink-0 mt-0.5" />
                      <div>
                        <span className="font-medium">
                          Detailed Explanations
                        </span>
                        <p className="text-sm text-gray-600">
                          Each question includes code examples and concepts
                        </p>
                      </div>
                    </div>
                    <div className="flex gap-3">
                      <CheckCircle2 className="h-5 w-5 text-blue-600 flex-shrink-0 mt-0.5" />
                      <div>
                        <span className="font-medium">
                          Organized by Category
                        </span>
                        <p className="text-sm text-gray-600">
                          Browse JavaScript, CSS topics easily
                        </p>
                      </div>
                    </div>
                    <div className="flex gap-3">
                      <CheckCircle2 className="h-5 w-5 text-blue-600 flex-shrink-0 mt-0.5" />
                      <div>
                        <span className="font-medium">
                          Keyboard Navigation
                        </span>
                        <p className="text-sm text-gray-600">
                          Use arrow keys to navigate between questions
                        </p>
                      </div>
                    </div>
                  </div>
                </div>

                <Separator />

                {/* How It Works */}
                <div>
                  <h3 className="font-semibold text-lg mb-4 flex items-center gap-2">
                    <Zap className="w-5 h-5 text-blue-600" />
                    How It Works
                  </h3>
                  <ol className="space-y-4">
                    <li className="flex gap-3">
                      <div className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-sm font-bold">
                        1
                      </div>
                      <div>
                        <span className="font-medium">Choose a Category</span>
                        <p className="text-sm text-gray-600">
                          Select JavaScript or CSS from the main page
                        </p>
                      </div>
                    </li>
                    <li className="flex gap-3">
                      <div className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-sm font-bold">
                        2
                      </div>
                      <div>
                        <span className="font-medium">Browse Questions</span>
                        <p className="text-sm text-gray-600">
                          Use the sidebar to navigate through questions
                        </p>
                      </div>
                    </li>
                    <li className="flex gap-3">
                      <div className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-sm font-bold">
                        3
                      </div>
                      <div>
                        <span className="font-medium">Learn & Practice</span>
                        <p className="text-sm text-gray-600">
                          Read explanations and understand concepts deeply
                        </p>
                      </div>
                    </li>
                  </ol>
                </div>

                <Alert className="bg-blue-50 border-blue-200">
                  <BookOpen className="h-4 w-4 text-blue-600" />
                  <AlertTitle className="text-blue-900">
                    Perfect for Interview Prep
                  </AlertTitle>
                  <AlertDescription className="text-blue-700">
                    Review these questions before your interviews. No AI credits
                    required - completely free!
                  </AlertDescription>
                </Alert>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>

        {/* Quick Start Guide */}
        <Card className="bg-gradient-to-br from-gray-50 to-gray-100 border-gray-200">
          <CardHeader>
            <CardTitle className="text-xl">🚀 Quick Start Guide</CardTitle>
            <CardDescription>
              First time here? Follow this recommended learning path
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4 md:grid-cols-3">
              <div className="flex flex-col items-center text-center space-y-2 p-4 bg-white rounded-lg">
                <div className="w-10 h-10 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center font-bold">
                  1
                </div>
                <h4 className="font-semibold">Learn Concepts</h4>
                <p className="text-sm text-gray-600">
                  Start with Learning to understand fundamentals
                </p>
              </div>
              <div className="flex flex-col items-center text-center space-y-2 p-4 bg-white rounded-lg">
                <div className="w-10 h-10 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center font-bold">
                  2
                </div>
                <h4 className="font-semibold">Test Knowledge</h4>
                <p className="text-sm text-gray-600">
                  Move to Practice to verify your understanding
                </p>
              </div>
              <div className="flex flex-col items-center text-center space-y-2 p-4 bg-white rounded-lg">
                <div className="w-10 h-10 rounded-full bg-green-100 text-green-700 flex items-center justify-center font-bold">
                  3
                </div>
                <h4 className="font-semibold">Prepare for Jobs</h4>
                <p className="text-sm text-gray-600">
                  Use Interview mode to practice real scenarios
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </Layout>
  );
}
